name: Optimus CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ 2.12.20, 2.13.15, 3.3.4 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Install lp-solve
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y lp-solve
          sudo wget https://sourceforge.net/projects/lpsolve/files/lpsolve/5.5.2.5/lp_solve_5.5.2.5_java.zip
          unzip lp_solve_5.5.2.5_java.zip
          sudo cp lp_solve_5.5_java/lib/ux64/liblpsolve55j.so /usr/lib/lp_solve && sudo ldconfig
      - name: Run tests
        run: sbt "++${{ matrix.scala }}" "core/test" "solver-oj/testOnly optimus.optimization.OJ*" "solver-lp/testOnly optimus.optimization.LP*"
        env:
          LD_LIBRARY_PATH: "/usr/lib/lp_solve"
